import Head from 'next/head'
import { blogPost } from '../../lib/data';

export default function BlogPost({title,date,content}) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {title}
        </h1>
        <h2>{date}</h2>
        <p>{content}</p>
      </main>
    </div>
  )
}

export async function getStaticProps({params}) {
    return {
      props: blogPost.find(blog=>blog.slug===params.slug), // will be passed to the page component as props
    }
  }

export async function getStaticPaths() {
    
    return {
      paths: blogPost.map(item =>({
          params:{
              slug: item.slug
          }
      })),
      fallback: false     
    };
}