import Head from 'next/head'
import Link from 'next/link'
import { blogPost } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <div>
        {blogPost.map((blog)=>(
          <div key={blog.slug}>
            <div>
              <Link href={`/blog/${blog.slug}`}><a><h2>{blog.title}</h2></a></Link>
            </div>
            <h3>{blog.date.toString()}</h3>
            <p>{blog.content}</p>
          </div>
        ))}
      </div>
    </div> 
  )
}
